# Docker compose for setting up a local development environment
version: '3.7'

services:
  database-service:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - backend-network
  user-service:
    image: user-service
    build:
      context: user/
      dockerfile: Dockerfile
    depends_on:
      - database-service
    environment:
      - USER_SVC_DB_HOST=database-service
      - USER_SVC_DB_PORT=5432
      - USER_SVC_DB_USER=postgres
      - USER_SVC_DB_PASSWORD=postgres
      - USER_SVC_DB_NAME=userdb
      - USER_SVC_DB_SSLMODE=disable
      - USER_SVC_JWT_SECRET=Thisisajwtsecret
      - USER_SVC_JWT_EXPIRY=48
      - USER_SVC_GRPC_HOST=user-service
      - USER_SVC_GRPC_PORT=50051
      - USER_SVC_HTTP_HOST=user-service
      - USER_SVC_HTTP_PORT=8080
      - USER_SVC_LOG_LEVEL=debug
    networks:
      - backend-network
  video-service:
    image: video-service
    build:
      context: video/
      dockerfile: Dockerfile
    depends_on:
      - database-service
    environment:
      - VIDEO_SVC_DB_HOST=database-service
      - VIDEO_SVC_DB_PORT=5432
      - VIDEO_SVC_DB_USER=postgres
      - VIDEO_SVC_DB_PASSWORD=postgres
      - VIDEO_SVC_DB_NAME=videodb
      - VIDEO_SVC_DB_SSLMODE=disable
      - VIDEO_SVC_GRPC_HOST=video-service
      - VIDEO_SVC_GRPC_PORT=50052
      - VIDEO_SVC_HTTP_HOST=video-service
      - VIDEO_SVC_HTTP_PORT=8090
      - VIDEO_SVC_LOG_LEVEL=debug
    networks:
      - backend-network
  api-gateway-service:
    image: api-gateway
    build:
      context: api-gateway/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - video-service
    env_file:
      - config.env
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
      